/**********************************************************************
 * Extern for RiveScript
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var RiveScript = function () {};
RiveScript.prototype = {
  "version": function () {},
  "Promise": function () {},
  "runtime": function () {},
  "say": function () {},
  "warn": function () {},
  "loadFile": function () {},
  "_ajaxLoadFile": function () {},
  "_nodeLoadFile": function () {},
  "loadDirectory": function () {},
  "stream": function () {},
  "parse": function () {},
  "sortReplies": function () {},
  "deparse": function () {},
  "stringify": function () {},
  "write": function () {},
  "setHandler": function () {},
  "setSubroutine": function () {},
  "setGlobal": function () {},
  "setVariable": function () {},
  "setSubstitution": function () {},
  "setPerson": function () {},
  "setUservar": function () {},
  "setUservars": function () {},
  "getVariable": function () {},
  "getUservar": function () {},
  "getUservars": function () {},
  "clearUservars": function () {},
  "freezeUservars": function () {},
  "thawUservars": function () {},
  "lastMatch": function () {},
  "initialMatch": function () {},
  "getUserTopicTriggers": function () {},
  "currentUser": function () {},
  "reply": function () {},
  "replyAsync": function () {}
};
/**********************************************************************
 * End Generated Extern for RiveScript
/**********************************************************************/
